version: '3'

services:
  web:
    image: neuroapi
    build: .
    command: "/bin/bash -l -c 'cd /code/neuroapi/neuro && neuroapi run -h 0.0.0.0'"
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/neuroapi.db
    volumes:
      - ./neuroapi:/code/neuroapi
      - ./db/:/db/
    ports:
      - "5000:5000"
